In [6]:
import numpy as np

In [25]:
l = np.random.rand(3,3)
y = np. random.rand(3,1)
total = np.hstack((l,y))
total

array([[ 0.27944707,  0.09787204,  0.776533  ,  0.53361915],
       [ 0.12739539,  0.15346886,  0.90499558,  0.80614808],
       [ 0.52437138,  0.47816038,  0.52240156,  0.40780154]])

In [26]:
l

array([[ 0.27944707,  0.09787204,  0.776533  ],
       [ 0.12739539,  0.15346886,  0.90499558],
       [ 0.52437138,  0.47816038,  0.52240156]])

In [27]:
y

array([[ 0.53361915],
       [ 0.80614808],
       [ 0.40780154]])

In [35]:
r = np.random.permutation(total)
r

array([[ 0.52437138,  0.47816038,  0.52240156,  0.40780154],
       [ 0.12739539,  0.15346886,  0.90499558,  0.80614808],
       [ 0.27944707,  0.09787204,  0.776533  ,  0.53361915]])

In [32]:
r[0:2,0:-1]

array([[ 0.52437138,  0.47816038,  0.52240156],
       [ 0.12739539,  0.15346886,  0.90499558]])

In [33]:
r[0:2,-1]

array([ 0.40780154,  0.80614808])

In [38]:
l = np.eye(2,2)
l

array([[ 1.,  0.],
       [ 0.,  1.]])

In [40]:
l != 0

array([[ True, False],
       [False,  True]], dtype=bool)

In [67]:
l = np.zeros((1,2))
r = np.array([float('inf'), float('inf')])
r[r==float('inf')]= 3


array([ 3.,  3.])

In [72]:
l.reshape(2,1)
l

array([[ 0.],
       [ 0.]])

In [76]:
for i in range(10,30,10):
    print(i)

10
20


In [77]:
print(12-12%10)

10


In [78]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [79]:
a = np.array([1,2,3,4,5])

In [87]:
b = np.ones(5)*10

In [89]:
np.power(b,a)

array([  1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05])

In [90]:
b = np.ones((3,3))

In [91]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [93]:
b = np.squeeze(b)

In [95]:
b.shape

(3, 3)

In [98]:
t = np.linspace(1,10,10)

In [100]:
t = np.ones((3,3))

In [101]:
t!=0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [102]:
A = np.array([[1,-1,1,0],[1,1,0,1]])

In [103]:
A

array([[ 1, -1,  1,  0],
       [ 1,  1,  0,  1]])

In [104]:
c = np.array([-2,-1,0,0])

In [112]:
 np.transpose(A) * np.transpose(np.array([-0.5,-1.5]))

array([[-0.5, -1.5],
       [ 0.5, -1.5],
       [-0.5, -0. ],
       [-0. , -1.5]])